name: Assign Reviewer By Label
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: glen
        id: glen-label
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: false
          reviewers: '["seokjin8678", "xxeol2"]'
          includeLabels: '["GLEN"]'
